# -*- coding: utf-8 -*-
"""mask-detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EAFm3H77bHqFlwbfSdyg8AjYOZWiGuGh
"""

# ===== CELL 1: Complete Setup & Model Initialization =====
import os
import cv2
import numpy as np
import pickle
import gradio as gr
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
from IPython.display import display, clear_output
import zipfile
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import time
import threading
import queue

# Install required packages
!pip install insightface onnxruntime-gpu gradio kaggle scikit-learn

# Kaggle API setup
os.environ['KAGGLE_USERNAME'] = 'soundaryats24cse'
os.environ['KAGGLE_KEY'] = 'ed8d7faa7b233596c35babba8761c00b'

# Check and download datasets with error handling
def download_and_extract():
    try:
        # Download datasets
        if not os.path.exists('face-mask-lite-dataset.zip'):
            print("📥 Downloading face-mask-lite-dataset...")
            !kaggle datasets download -d prasoonkottarathil/face-mask-lite-dataset

        if not os.path.exists('face-mask-dataset.zip'):
            print("📥 Downloading face-mask-dataset...")
            !kaggle datasets download -d omkargurav/face-mask-dataset

        # Extract datasets with checks
        if os.path.exists('face-mask-lite-dataset.zip'):
            print("📂 Extracting face-mask-lite-dataset...")
            with zipfile.ZipFile('face-mask-lite-dataset.zip', 'r') as zip_ref:
                zip_ref.extractall('mask_dataset1')
            print("✅ Dataset 1 extracted successfully!")

        if os.path.exists('face-mask-dataset.zip'):
            print("📂 Extracting face-mask-dataset...")
            with zipfile.ZipFile('face-mask-dataset.zip', 'r') as zip_ref:
                zip_ref.extractall('mask_dataset2')
            print("✅ Dataset 2 extracted successfully!")

    except Exception as e:
        print(f"⚠️ Dataset download error: {e}")
        print("🔄 Continuing with available data...")

download_and_extract()

# InsightFace model setup
import insightface
from insightface.app import FaceAnalysis

print("🚀 Loading InsightFace buffalo_l model...")

# Initialize face analysis with buffalo_l model (highest accuracy)
app = FaceAnalysis(name='buffalo_l', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640))

print("✅ InsightFace buffalo_l model loaded successfully!")

# Check GPU availability properly
try:
    gpu_available = any('CUDA' in str(provider) for provider in app.providers)
    print("✅ GPU acceleration enabled" if gpu_available else "⚠️ Using CPU")
except:
    print("📊 Processing acceleration configured")

# Global variables for the system
face_database = {}
training_data = []
training_labels = []
training_embeddings = []
label_encoder = LabelEncoder()
model_trained = False

# Performance tracking
frame_count = 0
fps_start_time = time.time()
current_fps = 0

# Threading for real-time processing
frame_queue = queue.Queue(maxsize=5)
result_queue = queue.Queue(maxsize=5)

# Recognition parameters
SIMILARITY_THRESHOLD = 0.6  # Higher = more strict
FACE_CONFIDENCE_THRESHOLD = 0.8

print("🎯 System initialized successfully!")
print(f"📊 Available datasets: {len([f for f in os.listdir('.') if 'mask_dataset' in f])} folders")
print("🔄 Ready for Cell 2 - Enhanced Training Module!")

# ===== CELL 2: Fixed Enhanced Training Module =====
import glob
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
import joblib
from collections import defaultdict

print("🚀 Starting Enhanced Training Module...")

# Advanced data preprocessing and augmentation
def preprocess_training_data():
    print("📊 Processing training datasets...")

    training_embeddings = []
    training_labels = []
    training_images = []

    dataset_paths = []

    # Check available datasets
    if os.path.exists('mask_dataset1'):
        dataset_paths.append('mask_dataset1')
    if os.path.exists('mask_dataset2'):
        dataset_paths.append('mask_dataset2')

    if not dataset_paths:
        print("⚠️ No datasets found, using registration-only mode...")
        return [], [], []

    label_count = defaultdict(int)
    person_id = 1

    for dataset_path in dataset_paths:
        print(f"📂 Processing {dataset_path}...")

        # Find all image files recursively
        image_extensions = ['*.jpg', '*.jpeg', '*.png', '*.bmp']
        image_files = []

        for ext in image_extensions:
            image_files.extend(glob.glob(f"{dataset_path}/**/{ext}", recursive=True))

        print(f"🔍 Found {len(image_files)} images in {dataset_path}")

        # Process images and create multiple identities
        for i, img_path in enumerate(image_files[:400]):  # Process more images
            try:
                # Create diverse labels for better training
                path_parts = img_path.lower().split('/')
                filename = os.path.basename(img_path).lower()

                # Determine label strategy
                if 'with_mask' in img_path.lower() or 'mask' in img_path.lower():
                    if 'without' in img_path.lower() or 'no_mask' in img_path.lower():
                        base_label = 'without_mask'
                    else:
                        base_label = 'with_mask'

                    # Create multiple person identities within mask categories
                    person_suffix = (i // 20) + 1  # Group every 20 images as same person
                    label = f"{base_label}_person_{person_suffix}"

                else:
                    # Create diverse person identities
                    label = f"person_{person_id}"
                    if i % 30 == 0:  # New person every 30 images
                        person_id += 1

                # Load and process image
                img = cv2.imread(img_path)
                if img is None:
                    continue

                img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

                # Face detection and embedding extraction
                faces = app.get(img_rgb)

                if faces:
                    face = faces[0]  # Take the first face
                    if face.det_score > 0.3:  # Lower threshold for more data
                        embedding = face.embedding

                        training_embeddings.append(embedding)
                        training_labels.append(label)
                        training_images.append(img_rgb)
                        label_count[label] += 1

                        if len(training_embeddings) % 25 == 0:
                            print(f"✅ Processed {len(training_embeddings)} faces...")

            except Exception as e:
                continue

    print(f"\n📊 Training Data Summary:")
    for label, count in label_count.items():
        print(f"  {label}: {count} samples")

    return training_embeddings, training_labels, training_images

# Execute training data preprocessing
training_embeddings, training_labels, training_images = preprocess_training_data()

if training_embeddings and len(set(training_labels)) > 1:
    print(f"\n🎯 Training advanced recognition model with {len(training_embeddings)} samples...")
    print(f"👥 Number of unique identities: {len(set(training_labels))}")

    # Convert to numpy arrays
    X = np.array(training_embeddings)
    y = np.array(training_labels)

    # Check if we have enough samples for train/test split
    if len(set(y)) >= 2 and len(X) >= 10:
        # Split data for training and validation
        X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

        # Train models
        print("🤖 Training ensemble models...")

        try:
            # Model 1: Support Vector Machine
            svm_model = SVC(kernel='rbf', probability=True, C=1.0, gamma='scale')
            svm_model.fit(X_train, y_train)
            svm_pred = svm_model.predict(X_val)
            svm_accuracy = accuracy_score(y_val, svm_pred)

            # Model 2: Random Forest
            rf_model = RandomForestClassifier(n_estimators=50, random_state=42, max_depth=8)
            rf_model.fit(X_train, y_train)
            rf_pred = rf_model.predict(X_val)
            rf_accuracy = accuracy_score(y_val, rf_pred)

            print(f"✅ SVM Model Accuracy: {svm_accuracy:.3f}")
            print(f"✅ Random Forest Accuracy: {rf_accuracy:.3f}")

            # Select best model
            if svm_accuracy > rf_accuracy:
                best_model = svm_model
                best_accuracy = svm_accuracy
                model_type = "SVM"
            else:
                best_model = rf_model
                best_accuracy = rf_accuracy
                model_type = "Random Forest"

            print(f"🏆 Best Model: {model_type} (Accuracy: {best_accuracy:.3f})")

            # Save the trained model
            joblib.dump(best_model, 'face_recognition_model.pkl')
            model_trained = True

        except Exception as e:
            print(f"⚠️ Model training error: {e}")
            print("🔄 Using cosine similarity method instead...")
            model_trained = False
            best_model = None
    else:
        print("⚠️ Insufficient data for supervised learning, using cosine similarity...")
        model_trained = False
        best_model = None

else:
    print("⚠️ Insufficient diverse data, using cosine similarity method...")
    model_trained = False
    best_model = None

# Create enhanced face database (works with any amount of data)
if training_embeddings:
    unique_labels = list(set(training_labels))
    for label in unique_labels:
        # Find all embeddings for this label
        label_indices = [i for i, l in enumerate(training_labels) if l == label]
        label_embeddings = [training_embeddings[i] for i in label_indices]

        if label_embeddings:
            # Use mean embedding for better representation
            mean_embedding = np.mean(label_embeddings, axis=0)
            face_database[label] = {
                'embedding': mean_embedding,
                'image': training_images[label_indices[0]],
                'samples': len(label_embeddings),
                'confidence': 0.9 if len(label_embeddings) > 5 else 0.7
            }

    print(f"\n🎯 Enhanced Face Database Created:")
    print(f"  👥 Total Identities: {len(face_database)}")
    for name, data in face_database.items():
        print(f"  {name}: {data['samples']} samples (confidence: {data['confidence']:.1f})")

# Enhanced recognition function with multiple methods
def enhanced_recognize_face(face_embedding, confidence_threshold=0.6):
    if not face_database:
        return None, 0.0

    # Method 1: Use trained model if available
    if model_trained and 'best_model' in globals() and best_model is not None:
        try:
            # Predict using trained model
            probabilities = best_model.predict_proba([face_embedding])
            classes = best_model.classes_

            max_prob_idx = np.argmax(probabilities[0])
            max_prob = probabilities[0][max_prob_idx]
            predicted_name = classes[max_prob_idx]

            if max_prob > confidence_threshold:
                return predicted_name, max_prob
        except:
            pass

    # Method 2: Cosine similarity fallback (always works)
    max_similarity = 0.0
    recognized_name = None

    for name, data in face_database.items():
        similarity = cosine_similarity([face_embedding], [data['embedding']])[0][0]

        # Adjust threshold based on training data quality
        adjusted_threshold = confidence_threshold * data['confidence']

        if similarity > max_similarity:
            max_similarity = similarity
            if similarity > adjusted_threshold:
                recognized_name = name

    return recognized_name, max_similarity

# Registration function for new users
def register_new_face(name, face_embedding, face_image):
    """Register a new face in the database"""
    if name in face_database:
        # Update existing entry with new sample
        existing_embedding = face_database[name]['embedding']
        samples = face_database[name]['samples']

        # Weighted average of embeddings
        new_embedding = (existing_embedding * samples + face_embedding) / (samples + 1)

        face_database[name]['embedding'] = new_embedding
        face_database[name]['samples'] += 1
        face_database[name]['confidence'] = min(0.95, face_database[name]['confidence'] + 0.1)

        print(f"✅ Updated {name} with new sample (total: {face_database[name]['samples']})")
    else:
        # Add new entry
        face_database[name] = {
            'embedding': face_embedding,
            'image': face_image,
            'samples': 1,
            'confidence': 0.8
        }
        print(f"✅ Registered new person: {name}")

print("✅ Enhanced Training Module Completed!")
print(f"🎯 Recognition Method: {'ML Model + Cosine Similarity' if model_trained else 'Cosine Similarity'}")
print("🔄 Ready for Cell 3 - Live Recognition Engine!")

# ===== CELL 3: Live Recognition Engine with Gradio =====
import gradio as gr
import cv2
import numpy as np
import time
import threading
from PIL import Image, ImageDraw, ImageFont
import io
import base64

print("🚀 Starting Live Recognition Engine...")

# Global variables for real-time processing
current_frame = None
processing_active = False
recognition_results = {}
fps_counter = 0
last_fps_time = time.time()

# Face landmark points for visualization
FACE_LANDMARKS = {
    'left_eye': 0,
    'right_eye': 1,
    'nose': 2,
    'mouth_left': 3,
    'mouth_right': 4
}

def draw_face_landmarks(image, landmarks, color=(0, 255, 0)):
    """Draw 5-point face landmarks"""
    draw = ImageDraw.Draw(image)
    for i, (x, y) in enumerate(landmarks):
        # Draw landmark points
        draw.ellipse([x-3, y-3, x+3, y+3], fill=color, outline=color)
    return image

def draw_face_box(image, bbox, name, confidence, color, landmarks=None):
    """Draw face bounding box with information"""
    draw = ImageDraw.Draw(image)

    # Draw bounding box
    x1, y1, x2, y2 = bbox
    draw.rectangle([x1, y1, x2, y2], outline=color, width=3)

    # Draw name and confidence
    text = f"{name}"
    if confidence > 0:
        text += f" ({confidence:.2f})"

    try:
        # Try to use a better font
        font = ImageFont.load_default()
    except:
        font = None

    # Text background
    text_bbox = draw.textbbox((x1, y1-30), text, font=font)
    draw.rectangle(text_bbox, fill=color, outline=color)
    draw.text((x1, y1-30), text, fill=(255, 255, 255), font=font)

    # Draw landmarks if provided
    if landmarks is not None:
        landmark_color = (0, 255, 0) if name != "UNKNOWN" else (255, 0, 0)
        image = draw_face_landmarks(image, landmarks, landmark_color)

    return image

def process_frame_for_recognition(frame):
    """Process a single frame for face recognition"""
    try:
        # Convert BGR to RGB for InsightFace
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Get faces from the frame
        faces = app.get(rgb_frame)

        results = []

        for face in faces:
            if face.det_score > 0.5:  # Confidence threshold
                # Get face embedding
                embedding = face.embedding

                # Recognize face
                name, confidence = enhanced_recognize_face(embedding, confidence_threshold=0.6)

                # Get bounding box
                bbox = face.bbox.astype(int)

                # Get landmarks
                landmarks = None
                if hasattr(face, 'kps') and face.kps is not None:
                    landmarks = face.kps.astype(int)

                results.append({
                    'name': name if name else "UNKNOWN",
                    'confidence': confidence,
                    'bbox': bbox,
                    'landmarks': landmarks,
                    'embedding': embedding
                })

        return results

    except Exception as e:
        print(f"Frame processing error: {e}")
        return []

def live_recognition_interface(frame):
    """Main function for live recognition"""
    global fps_counter, last_fps_time

    if frame is None:
        return None

    # Convert to OpenCV format
    frame_cv = cv2.cvtColor(np.array(frame), cv2.COLOR_RGB2BGR)

    # Process frame for recognition
    results = process_frame_for_recognition(frame_cv)

    # Convert back to PIL for drawing
    frame_pil = Image.fromarray(cv2.cvtColor(frame_cv, cv2.COLOR_BGR2RGB))

    # Draw results on frame
    for result in results:
        name = result['name']
        confidence = result['confidence']
        bbox = result['bbox']
        landmarks = result['landmarks']

        # Choose color based on recognition status
        if name == "UNKNOWN":
            color = (255, 0, 0)  # Red for unknown
        else:
            color = (0, 255, 0)  # Green for recognized

        # Draw face box and information
        frame_pil = draw_face_box(frame_pil, bbox, name, confidence, color, landmarks)

    # Calculate and display FPS
    current_time = time.time()
    if current_time - last_fps_time >= 1.0:
        fps_counter = 1.0 / (current_time - last_fps_time) if last_fps_time > 0 else 0
        last_fps_time = current_time

    # Add FPS counter to image
    draw = ImageDraw.Draw(frame_pil)
    fps_text = f"FPS: {fps_counter:.1f} | Faces: {len(results)}"
    draw.text((10, 10), fps_text, fill=(255, 255, 0))

    return frame_pil

def register_face_from_camera(frame, name):
    """Register a new face from camera input"""
    if frame is None or not name.strip():
        return "Please provide a valid image and name", None

    try:
        # Convert to OpenCV format
        frame_cv = cv2.cvtColor(np.array(frame), cv2.COLOR_RGB2BGR)
        rgb_frame = cv2.cvtColor(frame_cv, cv2.COLOR_BGR2RGB)

        # Get faces
        faces = app.get(rgb_frame)

        if not faces:
            return "No face detected in the image. Please ensure good lighting and face is visible.", None

        if len(faces) > 1:
            return "Multiple faces detected. Please ensure only one face is in the frame.", None

        face = faces[0]

        # Check quality
        if face.det_score < 0.7:
            return "Face quality too low. Please improve lighting and face clarity.", None

        # Extract embedding
        embedding = face.embedding

        # Register the face
        register_new_face(name.strip(), embedding, rgb_frame)

        # Create confirmation image
        confirmation_img = Image.fromarray(rgb_frame)
        bbox = face.bbox.astype(int)
        confirmation_img = draw_face_box(
            confirmation_img, bbox, name.strip(), face.det_score, (0, 255, 0)
        )

        return f"✅ Successfully registered {name.strip()}!", confirmation_img

    except Exception as e:
        return f"Registration error: {str(e)}", None

# Create Gradio interface
def create_gradio_interface():
    print("🎨 Creating Gradio Interface...")

    with gr.Blocks(title="Face Recognition System", theme=gr.themes.Soft()) as demo:
        gr.Markdown("""

        """)

        with gr.Tab("📹 Live Recognition"):
            gr.Markdown("### Real-time Face Recognition")

            with gr.Row():
                with gr.Column():
                    live_input = gr.Image(
                        sources=["webcam"],
                        streaming=True,
                        type="pil"
                    )

                with gr.Column():
                    live_output = gr.Image(
                        type="pil",
                        label="Recognition Results"
                    )

                    recognition_info = gr.Markdown(f"""
                    **System Status:** ✅ Ready

                    **Recognition Database:** {len(face_database)} identities

                    **Legend:**
                    - 🟢 Green Box: Recognized Person
                    - 🔴 Red Box: Unknown Person
                    - 🟡 Yellow Dots: Face Landmarks
                    """)

            # Connect live recognition
            live_input.stream(
                fn=live_recognition_interface,
                inputs=[live_input],
                outputs=[live_output],
                stream_every=0.1,  # Process every 100ms
                show_progress=False
            )

        with gr.Tab("👤 Register New Person"):
            gr.Markdown("### Register New Identity")

            with gr.Row():
                with gr.Column():
                    register_image = gr.Image(
                        sources=["webcam"],
                        type="pil",
                        label="Capture Registration Photo"
                    )
                    register_name = gr.Textbox(
                        label="Person's Name",
                        placeholder="Enter name here..."
                    )
                    register_btn = gr.Button("📝 Register Person", variant="primary")

                with gr.Column():
                    register_output_img = gr.Image(
                        type="pil",
                        label="Registration Confirmation"
                    )
                    register_status = gr.Textbox(
                        label="Registration Status",
                        interactive=False
                    )

            # Connect registration
            register_btn.click(
                fn=register_face_from_camera,
                inputs=[register_image, register_name],
                outputs=[register_status, register_output_img]
            )

        with gr.Tab("📊 System Info"):
            gr.Markdown("### Database Statistics")

            def get_database_info():
                if not face_database:
                    return "No identities registered yet."

                info = f"**Total Registered Identities:** {len(face_database)}\n\n"
                for name, data in face_database.items():
                    info += f"- **{name}**: {data['samples']} samples (confidence: {data.get('confidence', 0.8):.1f})\n"

                return info

            database_info = gr.Markdown(get_database_info())
            refresh_btn = gr.Button("🔄 Refresh Database Info")

            refresh_btn.click(
                fn=get_database_info,
                outputs=[database_info]
            )

    return demo

# Launch the interface
print("🚀 Launching Live Recognition Interface...")
demo = create_gradio_interface()

# Configure and launch
demo.launch(
    debug=True,
    share=True,  # Creates public link
    server_name="0.0.0.0",
    server_port=7860,
    show_error=True
)

print("✅ Live Recognition Engine Started!")
print("📱 Open the Gradio interface to start recognition")
print("🔄 Ready for Cell 4 - Advanced Display Features!")

